USE [master]
GO

CREATE DATABASE [IAG]
ON (
	NAME = IAG_DATA,
	FILENAME = 'C:\DB\IAG\IAG.mdf',
	SIZE = 10MB,
	FILEGROWTH = 5MB
)
LOG ON (
	NAME = IAG_LOG,
	FILENAME = 'C:\DB\IAG\IAG.ldf',
	SIZE = 5MB,
	FILEGROWTH = 5MB
);
GO

CREATE LOGIN [iag] WITH PASSWORD = 'iagpass', CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF, DEFAULT_DATABASE = [IAG];
GO

USE [IAG]
GO

CREATE USER [iag] FROM LOGIN [iag];
GO

ALTER ROLE [db_datareader] ADD MEMBER [iag];
GO

ALTER ROLE [db_datawriter] ADD MEMBER [iag];
GO

GRANT EXECUTE ON DATABASE::IAG TO [iag];

USE [master]
GO

